### ISSUE TITLE
Android 5.0.2: Not possible to install together with OI Notepad 

### ISSUE THREAD

**Issue by HRio** [openintents/safe#14]
Hi,

With Android 5.0.2 (cm12) it is not possible to install "OI Safe" when "OI Notepad" is already installed.

The result is error -505 (INSTALL_FAILED_DUPLICATE_PERMISSION).

Can you please investigate this?

Thanks.

**Comment by friedger** [comment]
Acknowledged. It does not work the other way around neither.

We will need to update both apps. Not sure whether it will work of the old
versions are ready installed. Will investigate...
Am 30.03.2015 23:23 schrieb "HRio" <notifications@github.com>:

**Comment by rmceoin** [comment]
Just a quick guess, but is it because Notepad offers the same permission that only Safe should offer?  Shouldn't it just be that Safe has this permission listed and Notepad only has a <uses-permission> reference?

https://github.com/openintents/notepad/blob/master/NotePad/AndroidManifest.xml#L260

    <permission android:name="org.openintents.safe.ACCESS_INTENTS"
			android:protectionLevel="dangerous"
			android:label="@string/oi_safe_permission_intents"
        	android:description="@string/oi_safe_permission_intents_descr" />

If true, the potential solution is to remove it from Notepad's manifest.

**Comment by friedger** [comment]
A new version has been pushed to beta:
https://play.google.com/apps/testing/org.openintents.safe

**Comment by friedger** [comment]
You have to update NotePad first: https://play.google.com/apps/testing/org.openintents.notepad
