### ISSUE TITLE
The cache of the screen remains in the app switcher

### ISSUE THREAD

**Issue by zafarella** [openintents/safe#17]
making vulnerable sensitive info (to be read without authentication)

**Comment by friedger** [comment]
Should be fixed by https://github.com/openintents/safe/commit/16938b4a93143b60d34bf76b82ce1dc7ed1bab18.

I'll update the app. Interested in beta testing? Join the power user group https://plus.google.com/communities/102097420123460267614

**Comment by dicer** [comment]
Is this the security hole on rooted devices mentioned in the playstores "whats new"?

**Comment by zafarella** [comment]
it doesn't matter is it rooted or not. When you open the app and call app switcher, you will be able to see the screen snapshot. This issue is about this.

**Comment by dicer** [comment]
I know what THIS issue is about. I saw it some years ago.
There has been a new release to the playstore and in the whats new section it says that there was a security hole on rooted devices fixed. So I was wondering whether it was this one or something else. Can't find any other commits that one could describe as a security flaw.

**Comment by zafarella** [comment]
@dicer  Sorry, no idea. Sorry if were rude, didn't meant that. I think it is not related to device being rooted.

**Comment by friedger** [comment]
The issue mentioned in the "What's new section" refers to the PNRG fix http://android-developers.blogspot.be/2013/08/some-securerandom-thoughts.html

**Comment by friedger** [comment]
fixed in 1.5.2

**Comment by dicer** [comment]
Ah ok. So this bug is not mentioned in the play store description then?

I thought the PNRG fix was "Updates and fix for Jelly Bean (4.1)"
because the PNRG fix gets only applied on those versions.

I still don't the connection to rooted devices in "Fix security hole in
rooted devices" though. PNRG should be a problem on any device that
isn't fixed, right?

**Comment by friedger** [comment]
Actually you are right. It has been a while.. 

This could be the commit referring to rooted device issue. (more guessing than anything else):
https://github.com/openintents/safe/commit/6bd7a49c1e26d382dc69e32a6e8886fd281afc98
